name: app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.11.2
  path_provider: ^2.0.10
  gallery_saver_plus: ^3.2.9

  http: ^1.5.0
  equatable: ^2.0.0
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.2.2
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  mask_text_input_formatter: ^2.1.0
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^9.2.4

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

